# Generated by Django 4.1.7 on 2023-02-18 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chort', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='hash',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='link',
            name='original',
            field=models.CharField(max_length=1000),
        ),
    ]
