# Generated by Django 4.1.7 on 2023-02-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chort', '0004_location_browser_location_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='QRCode'),
        ),
    ]
