# Generated by Django 4.1.7 on 2023-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chort', '0005_link_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='qr_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
