# Generated by Django 4.1.7 on 2023-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chort', '0008_alter_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
