# Generated by Django 4.1.7 on 2023-02-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chort', '0009_location_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
