# Generated by Django 4.1.7 on 2023-02-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chort', '0010_alter_location_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='custome',
            field=models.BooleanField(default=False),
        ),
    ]
